"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import { ApolloProvider } from "@apollo/client";
import client from "../apollo-client";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Reddit 2.0 Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ApolloProvider client={client}>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          <div className="h-screen overflow-y-scroll bg-slate-200">
            <Header />
            <div>{children}</div>
          </div>
        </body>
      </html>
    </ApolloProvider>
  );
}
